matrix:
  ARCH:
    - armhf
    # - amd64
  VERSION:
    # - "0.20.5"
    - "master"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    - docker daemon --storage-driver overlay --graph /drone/docker &
    - cd $$VERSION/$$ARCH
    - IID=$(docker build --quiet --force-rm --file Dockerfile.build .)
    - CID=$(docker create $IID /bin/true)
    - docker cp $CID:/build build/
    - docker rm --force $CID
  when:
    matrix:
      ARCH: armhf

publish:
  docker:
    file: "$$VERSION/$$ARCH/Dockerfile"
    context: "$$VERSION/$$ARCH"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/cadvisor
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
