matrix:
  ARCH:
    - armhf
    # - amd64
  VERSION:
    # - "0.20.5"
    - "master"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    - docker daemon --storage-driver overlay &
    - sleep 2
    - cd $$VERSION/$$ARCH
    - docker build --tag build-image-temp --file Dockerfile.build .
    - docker run --rm --volume $PWD:/target build-image-temp
    - ./cadvisor -version
  when:
    matrix:
      ARCH: armhf

publish:
  docker:
    file: "$$VERSION/$$ARCH/Dockerfile"
    context: "$$VERSION/$$ARCH"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/cadvisor
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
