FROM armhfbuild/golang:1.5.3-alpine
RUN apk --update add git g++ gcc make linux-headers

# RUN go get github.com/google/cadvisor

RUN go get github.com/tools/godep \
  && godep go build -a github.com/google/cadvisor

CMD cp ./bin/cadvisor /target/cadvisor
